import os
import sys
import json
from github import Github
import openai
import pandas as pd

# 환경 변수 로드
GH_TOKEN = os.getenv('GH_TOKEN')
REPO_NAME = os.getenv('REPO_NAME')
MODE = os.getenv('MODE')
LIMIT = int(os.getenv('LIMIT', 10))
OPENAI_API_KEY = os.getenv('OPENAI_API_KEY')

# GitHub 클라이언트 초기화
g = Github(GH_TOKEN)
repo = g.get_repo(REPO_NAME)

# OpenAI 클라이언트 초기화 (대량 모델링용)
if OPENAI_API_KEY:
    openai.api_key = OPENAI_API_KEY
    client = openai.OpenAI(api_key=OPENAI_API_KEY)

def ai_modeling(title, body):
    """
    [대량 모델링 기능]
    이슈 내용을 분석하여 요약, 타입(버그/기능), 중요도를 반환
    """
    if not OPENAI_API_KEY:
        return {"summary": "AI Key Missing", "type": "unknown", "priority": "low"}
    
    prompt = f"""
    Analyze this GitHub issue.
    Title: {title}
    Body: {body}
    
    Return JSON format:
    {{
        "summary": "One sentence summary in Korean",
        "type": "bug" or "feature" or "question",
        "priority": "high" or "medium" or "low",
        "reason": "Short reason for priority"
    }}
    """
    
    try:
        response = client.chat.completions.create(
            model="gpt-4o-mini", # 또는 사용 가능한 모델
            messages=[{"role": "user", "content": prompt}],
            response_format={"type": "json_object"}
        )
        return json.loads(response.choices[0].message.content)
    except Exception as e:
        print(f"Error in AI inference: {e}")
        return None

def bulk_create():
    """
    [대량 생성 기능]
    테스트를 위해 가상의 이슈들을 대량으로 생성합니다.
    실무에서는 CSV 파일을 읽어서 생성하도록 변경 가능.
    """
    print(f"🚀 Starting Bulk Create (Limit: {LIMIT})...")
    dummy_issues = [
        {"title": "[Bug] 로그인 페이지 500 에러", "body": "로그인 시 간헐적으로 서버 에러 발생"},
        {"title": "[Feature] 다크 모드 추가 요청", "body": "사용자 경험 향상을 위해 다크 모드 필요"},
        {"title": "[Docs] API 문서 최신화", "body": "v2 API 변경 사항이 문서에 반영되지 않음"},
        # ... 필요한 만큼 패턴 추가
    ]
    
    count = 0
    for item in dummy_issues:
        if count >= LIMIT: break
        issue = repo.create_issue(title=item['title'], body=item['body'])
        print(f"Created issue #{issue.number}: {item['title']}")
        count += 1

def analyze_and_reflect():
    """
    [대량 추출 + 대량 모델링 + 대량 반영]
    1. 오픈된 이슈 추출
    2. AI 모델링 (분석)
    3. 라벨/댓글 반영
    """
    print(f"🔍 Starting Analysis & Reflection (Limit: {LIMIT})...")
    issues = repo.get_issues(state='open')
    
    processed = 0
    for issue in issues:
        if processed >= LIMIT: break
        
        # 이미 봇이 처리한 흔적(라벨 등)이 있으면 스킵하는 로직 추가 가능
        print(f"Processing #{issue.number}: {issue.title}")
        
        # 1. 모델링 (AI 분석)
        analysis = ai_modeling(issue.title, issue.body)
        
        if analysis:
            # 2. 반영 (Reflection) - 라벨링
            labels_to_add = []
            if analysis['type'] == 'bug': labels_to_add.append('bug')
            if analysis['type'] == 'feature': labels_to_add.append('enhancement')
            if analysis['priority'] == 'high': labels_to_add.append('high-priority')
            
            # 라벨 추가 (기존 라벨 유지하며 추가)
            if labels_to_add:
                issue.add_to_labels(*labels_to_add)
                print(f"   -> Added labels: {labels_to_add}")

            # 3. 반영 (Reflection) - 댓글 달기
            comment_body = f"""
### 🤖 AI Analysis Report
| Category | Result |
| --- | --- |
| **Type** | {analysis['type']} |
| **Priority** | {analysis['priority']} |
| **Summary** | {analysis['summary']} |
| **Reason** | {analysis['reason']} |

*This comment is automatically generated by AI Ops.*
            """
            issue.create_comment(comment_body)
            print(f"   -> Commented on #{issue.number}")
            
        processed += 1

def export_report():
    """
    [대량 추출]
    이슈 데이터를 CSV로 저장
    """
    print(f"📊 Exporting Report...")
    issues = repo.get_issues(state='all') # closed 포함
    data = []
    
    count = 0
    for issue in issues:
        if count >= LIMIT: break
        data.append({
            "number": issue.number,
            "title": issue.title,
            "state": issue.state,
            "labels": [l.name for l in issue.labels],
            "created_at": issue.created_at,
            "url": issue.html_url
        })
        count += 1
    
    df = pd.DataFrame(data)
    df.to_csv("issue_report.csv", index=False, encoding='utf-8-sig')
    print("✅ issue_report.csv created.")

# 메인 실행 로직
if __name__ == "__main__":
    if MODE == 'bulk_create_demo':
        bulk_create()
    elif MODE == 'analyze_and_reflect':
        analyze_and_reflect()
    elif MODE == 'export_report':
        export_report()
    else:
        print("Unknown Mode")
        sys.exit(1)
